version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      STRAPI_BASE_URL: ${STRAPI_BASE_URL}
      APP_NAME: ${APP_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_LOG_GROUP_NAME: ${AWS_LOG_GROUP_NAME}
      AWS_LOG_STREAM_NAME: ${AWS_LOG_STREAM_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
