import { ROLES } from "../constants/userRoles";
import { PERMISSIONS } from "../constants/userPermissions";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.LIST_POSTS,
    PERMISSIONS.SHOW_POSTS,
    // PERMISSIONS.CREATE_POSTS,
    // PERMISSIONS.UPDATE_POSTS,
    PERMISSIONS.ACCESS_SETTINGS,
  ],
  [ROLES.SUPER_ADMIN]: [
    PERMISSIONS.LIST_POSTS,
    PERMISSIONS.CREATE_POSTS,
    PERMISSIONS.SHOW_POSTS,
    PERMISSIONS.UPDATE_POSTS,
    PERMISSIONS.DELETE_POSTS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.ACCESS_SETTINGS,
  ],
};
